apiVersion: cli.kyverno.io/v1beta1
kind: KyvernoTest
metadata:
  name: block-images
spec:
  policies: 
  - policy.yaml
  resources:
    my_resource_pool: 
    - resource1.yaml
  results:
  - policy: cm-variable-example
    rule: example-configmap-lookup
    resources:
    - old: my_resource_pool:v1/default/test-env-test
    kind: Pod
    result: pass
  - policy: cm-variable-example
    rule: example-configmap-lookup
    resources:
    - old: my_resource_pool:v1/default/test-env-dev
    kind: Pod
    result: fail
  variables:
    policies:
    - name: cm-variable-example
      rules:
        - name: example-configmap-lookup
          values:
            dictionary:
              data: 
                env: test
      resources:
        - name: test-env-test
          values:
            request.object.metadata.name: test-env-test
        - name: test-env-dev
          values:
            request.object.metadata.name: test-env-dev